eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      ## Product Service Route
      routes[0].id: product-service
      routes[0].uri: lb://product-service
      routes[0].predicates[0]: Path=/api/product

      ## Order Service Route
      routes[1].id: order-service
      routes[1].uri: lb://order-service
      routes[1].predicates[0]: Path=/api/order

      ## Discover Server Route(http://localhost:9090/eureka/web 진입시 localhost:8761 되도록 설정
      routes[2].id: discovery-server
      routes[2].uri: http://localhost:8761
      routes[2].predicates[0]: Path=/eureka/web
      routes[2].filters[0]: SetPath=/

      ## Discover Server Static Resources Route
      routes[3].id: discovery-server-static
      routes[3].uri: http://localhost:8761
      routes[3].predicates[0]: Path=/eureka/**
  main:
    web-application-type: reactive
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler.probability:1.0

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

server:
  port: 9090




